# Generated by Django 2.2.3 on 2020-10-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_auto_20201029_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(default='pokeball.jpg', upload_to='', verbose_name='изображение'),
            preserve_default=False,
        ),
    ]
