# Generated by Django 2.2.3 on 2020-11-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0014_pokemonelementtype_strong_against'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='element_type',
            field=models.ManyToManyField(blank=True, to='pokemon_entities.PokemonElementType'),
        ),
        migrations.AlterField(
            model_name='pokemonelementtype',
            name='image',
            field=models.ImageField(default='fire.png', upload_to='', verbose_name='изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemonelementtype',
            name='strong_against',
            field=models.ManyToManyField(blank=True, to='pokemon_entities.PokemonElementType', verbose_name='Силён против'),
        ),
    ]
